### ISSUE TITLE
Metadata not loading completely into site (missing Episodes from tpdb)

### ISSUE THREAD

**Issue by laynlownc** [Whisparr/Whisparr#55]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Tried importing a move from Evil Angel that I can find in TDPB ( /scenes/evil-angel-sofia-curly-samantha-rone-dp-4-way) but it is not loading is whisparr

### Expected Behavior

I would expect to find it in the list. Tried a refresh, Also tried removing and adding again multiple times. 

### Steps To Reproduce

Missing a lot of 2022, 2021, and so on. 

### Environment

```markdown
- OS: Unraid Version: 6.9.2
- Whisparr: 2.0.0.134
- Docker Install: YES
- Using Reverse Proxy: no
- Browser:Chrome
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/laynlownc/fcbcdd2736edace6feb400e7233123ff

**Comment by thezak48** [comment]
If TPDB has it listed as a Movie, it won't be added to whisparr as we currently don't have movie support in v2 as of yet

**Comment by arth6250** [comment]
Same issue here with Evil Angel, tpdb listing a bunch of scenes for 2022, but it looks like whisparr doesnt have anything prior to september 26th for the 2022 season.

**Comment by Qstick** [comment]
This is due to a limitation of TPDB API of being able to retrieve 10000 scenes per site. We've got a bit of a workaround for this in our metadata v3 server which we are switching to soon.

**Comment by miracle152005** [comment]
Did something change with 2.0.0.243. Since yesterday he removed a lot of scenes from the added sites and they are still on TBPD.

**Comment by Qstick** [comment]
> Did something change with 2.0.0.243. Since yesterday he removed a lot of scenes from the added sites and they are still on TBPD.

Different issue, but it's fixed now.

**Comment by mat926** [comment]
I'm having the same issue with TPDB ID: 2144 . It's not loading the rest of the years for me.

**Comment by frankmagon** [comment]
Can confirm this is a widespread issue, I'm currently on v2.0.0.289
A couple of examples:

tpdb: **7572**
- First Scene: 2020-12-21 - First Scene in Whisparr: 2021-08-05
- Latest Scene: 2023-07-21 - Latest Scene in Whisparr: 2023-05-11

tpdb: **2888**
- First Scene: 2017-09-15 - First Scene in Whisparr: 2019-04-07
- Latest Scene: 2023-11-13 - Latest Scene in Whisparr: 2023-11-09

tpdb: **6059**
- First Scene: **2019-09-01** - First Scene in Whisparr: **2019-08-31**
- Latest Scene: **2023-11-03** - Latest Scene in Whisparr: **2023-10-19**


Wasn't an issue a few months ago, I haven't been able to pinpoint when, but it was pre nightly v2.0.0.208 (anything later than that and search doesn't work).

Also not an issue on Plex TPDB plugin, screenshot shows first episode of tpdb: **7572** found in Plex search vs the first episode listed in Whisparr:

![image](https://github.com/Whisparr/Whisparr/assets/151069739/51965c38-1a46-4e96-ab14-fbc1299cb8de)

**Comment by shentokozil** [comment]
this problem seems to be on a lot of sites, I have noticed boundgangbangs (kink.com) claims to have 1 scene on whisparr, tpdb lists loads, I've found similar problems with a few other kink.com site lists, the scenes are findable in tpdb, but not whisparr

**Comment by Nobrumski** [comment]
I am still seeing this with the update on main, 2.0.0.313. First episode in Whisparr starts at s2:e12 but tpdb starts at s1e1 in tpdb ID 126.

**Comment by Ceequester** [comment]
Is there anywhere we can contribute to the metadata server or any updates on the metadata server? @Qstick

**Comment by Gykes** [comment]
This is just a caching issue. If anyone needs refresh then ping me in Whisparr discord.
